### ISSUE TITLE
Barfing on @supports

### ISSUE THREAD

**Issue by serates** [dart-lang/csslib#50]
[StylesheetCompiler on ares|lib/src/mdc/components/layout/scss/variables.css]:
Errors parsing CSS:
error on line 50, column 4: expected } after ruleset for @media
  @supports (display: grid) {
   ^^^^^^^^
error on line 56, column 1: premature end of file unknown CSS
}
I hit this as i'm trying to take some sass from material design components for web from material.io this one originated from using the mdc-layout-grid sass

**Comment by leonsenft** [comment]
> `error on line 50, column 4: expected } after ruleset for @media`

This actually looks like it's an issue with the `@media` rule before it

Are you running a SASS to CSS transformer as part of your build, or did you convert it ahead of time? If the latter do you have the CSS file for reference so I can see what's wrong with the `@media` rule please?

**Comment by serates** [comment]
Yeah i'm using transform_sass, but i've also tried the dart_sass_transformer here is the css compiled

[layout.css.txt](https://github.com/dart-lang/csslib/files/1002735/layout.css.txt)

**Comment by leonsenft** [comment]
Thanks for providing the CSS! I'll have to investigate a little further but I have a suspicion that the `var(--mdc-layout-grid-gutter, 16px)` in the previous `width` declaration is the issue.
