### ISSUE TITLE
Upgrade from comment-based generics syntax

### ISSUE THREAD

**Issue by srawlins** [dart-lang/csslib#61]
The comment-based generics syntax will be removed from the Dart SDK tools (like DDC, analyzer) "soon." dart-lang/sdk#28796

Such syntax (like in [_mergeVal](https://github.com/dart-lang/csslib/blob/master/lib/src/property.dart#L1248)) needs to be updated, and the minimum Dart SDK in [pubspec.yaml](https://github.com/dart-lang/http_parser/blob/master/pubspec.yaml#L16) needs to be bumped to 1.21, when the [real, non-comment-based syntax was introduced](https://github.com/dart-lang/csslib/blob/master/pubspec.yaml#L7).

**Comment by keertip** [comment]
https://codereview.chromium.org/2985973002/
